# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cb2a7df12e578b15dde7a35ac1fb183b7bcdbee95ce702a10e6be6cde2cff004cfdcccce4c9da4bc03e2e8f01dfded2a9bf009e0e8b587cc946f0036c71e8d7

test:
  secret_key_base: 8bb09d9aaafc95b66c48601f0582aa5459b2444f22a14df922bea5c4fa2b77bc3a0af57594beeb761aab653aacf295bf40e7b7e5a5b3e136152f6274b64823bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
